# Generated by Django 5.1.1 on 2024-10-08 18:56

import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[validators.pet_photo_max_size_validator]),
        ),
    ]
